Name:           ros-indigo-move-base-flex
Version:        0.2.1
Release:        0%{?dist}
Summary:        ROS move_base_flex package

Group:          Development/Libraries
License:        BSD
URL:            http://wiki.ros.org/move_base_flex
Source0:        %{name}-%{version}.tar.gz

BuildArch:      noarch

Requires:       ros-indigo-mbf-abstract-core
Requires:       ros-indigo-mbf-abstract-nav
Requires:       ros-indigo-mbf-costmap-core
Requires:       ros-indigo-mbf-costmap-nav
Requires:       ros-indigo-mbf-msgs
Requires:       ros-indigo-mbf-simple-nav
BuildRequires:  ros-indigo-catkin

%description
Move Base Flex (MBF) is a backwards-compatible replacement for move_base. MBF
can use existing plugins for move_base, and provides an enhanced version of the
planner, controller and recovery plugin ROS interfaces. It exposes action
servers for planning, controlling and recovering, providing detailed information
of the current state and the plugin’s feedback. An external executive logic can
use MBF and its actions to perform smart and flexible navigation strategies.
Furthermore, MBF enables the use of other map representations, e.g. meshes or
grid_map This package is a meta package and refers to the Move Base Flex stack
packages.The abstract core of MBF – without any binding to a map representation
– is represented by the mbf_abstract_nav and the mbf_abstract_core. For
navigation on costmaps see mbf_costmap_nav and mbf_costmap_core.

%prep
%setup -q

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake .. \
        -UINCLUDE_INSTALL_DIR \
        -ULIB_INSTALL_DIR \
        -USYSCONF_INSTALL_DIR \
        -USHARE_INSTALL_PREFIX \
        -ULIB_SUFFIX \
        -DCMAKE_INSTALL_LIBDIR="lib" \
        -DCMAKE_INSTALL_PREFIX="/opt/ros/indigo" \
        -DCMAKE_PREFIX_PATH="/opt/ros/indigo" \
        -DSETUPTOOLS_DEB_LAYOUT=OFF \
        -DCATKIN_BUILD_BINARY_PACKAGE="1" \

make %{?_smp_mflags}

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/indigo/setup.sh" ]; then . "/opt/ros/indigo/setup.sh"; fi
cd obj-%{_target_platform}
make %{?_smp_mflags} install DESTDIR=%{buildroot}

%files
/opt/ros/indigo

%changelog
* Wed Oct 03 2018 Sebastian Pütz <spuetz@uos.de> - 0.2.1-0
- Autogenerated by Bloom

